
server:
  port: 8082
  
spring:
  application:
    name: client-service-2
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
 
logging:
  file:
    name: D:/learnings/backend/java/spring_boot/microservice/microservice_practice/client-service-2/log/client-service-2.log
      